#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../../.." && pwd)"
PROFILE="${CLUSTODIAN_M13_SCALE_PROFILE:-scale-100-10k}"
SEED="${CLUSTODIAN_M13_SCALE_SEED:-187231}"

case "$PROFILE" in
  scale-100-10k|scale-250-50k) ;;
  *) echo "unsupported scale profile: $PROFILE" >&2; exit 2 ;;
esac

CLUSTODIAN_M13_PROFILE="$PROFILE" \
CLUSTODIAN_M13_PR_SEEDS="$SEED" \
CLUSTODIAN_M13_PR_STEPS=0 \
CLUSTODIAN_M13_SCENARIO_TIMEOUT_SECONDS="${CLUSTODIAN_M13_SCALE_TIMEOUT_SECONDS:-1800}" \
CLUSTODIAN_CHAOS_QUIESCENCE_TIMEOUT_MILLISECONDS="${CLUSTODIAN_M13_SCALE_QUIESCENCE_TIMEOUT_MILLISECONDS:-300000}" \
CLUSTODIAN_CHAOS_CONTROLLER_LEASE_TTL_MS="${CLUSTODIAN_M13_SCALE_CONTROLLER_LEASE_TTL_MS:-30000}" \
CLUSTODIAN_CHAOS_PARTICIPANT_LEASE_TTL_MS="${CLUSTODIAN_M13_SCALE_PARTICIPANT_LEASE_TTL_MS:-120000}" \
CLUSTODIAN_M13_METRICS_CHECKER="$ROOT/tools/clustodian-chaos/scripts/check-scale-metrics.py" \
  "$ROOT/reference/apache-helix/verify-m13.sh"
