[package]
name = "clustodian-job-workers"
version = "0.1.0"
edition = "2021"
publish = false

[features]
shuttle = []

[dependencies]
clustodian = { path = "../.." }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.53.1", features = [
    "macros",
    "net",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }

[dev-dependencies]
clustodian-test-support = { path = "../../tools/clustodian-test-support" }
etcd-client = "0.15.0"
tempfile = "3.27.0"
